version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-example
    ports:
      - "8000:8000"
    restart: "no"
    command: sh -c "echo 'Starting faulty version...'; sleep 2; exit 1"